name: sync
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: npm install
      - run: npm run sync
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
