name: sync
on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: npm install
      - run: npm run sync
