name: sync
on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: sync
        run: npm run sync
